### PR TITLE
Fix `Key not found` error while loading extensions

### LINKED ISSUE #1238: The extensions cannot be fetched from the KV store
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.2   | 4301 |

**Description**

The application failes to load the extensions as it sends a request to the backend with no API key, so the data cannot be recovered from the SPlunk KV store (no primary key is provided). 

This is caused by a bad design on the JS code, as the `getExtensionsKey()` method on the `apiIndexStorageService` returns the API ID store on the session storage or throws an error which is later catched on the `getExtensionsById()` on the `currentDataService`, taking the ID given as parameter.

The correction of some errors marked by ESlint led to this bug, as the catch/throw block was removed.

**Steps to reproduce**

1. Go to 'Overview'
4. See the error

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by AlexRuiz7**
Closes #1238 

Summary
----------
This PR fixes an error introduced by maintenance tasks run on 4.3.

The design and logic of the functions involved on this erros has been slightly changed.

To test
-----------

1. Go to Overview
2. Check that no error toast is shown
3. Open the browser's dev tools and go to Application
4. Check that there is a `extensions` field on the Sessoin Storage, and that it is not empty.
5. On the dev tools, go to network and look for the a request named `extensions`, and check that a valid key (not empty or null) has been sent as payload.

### CODE REVIEW

**Review by Machi3mfl — DISMISSED** [review]
LGTM!

**Review by asteriscos — DISMISSED** [review]
LGTM :heavy_check_mark:

File: SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js [hunk 1]
```diff
@@ -86,11 +86,8 @@ define(['../module'], function (app) {
             return parsedExtensions[apiId]
```
Comment (asteriscos) [inline SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js:86]: Not every logical path will return a value. To write it consistently, it would be better if it had 1 return statement that will always be executed, even if the returned value is falsy one.

Comment (AlexRuiz7) [reply SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js]: The whole function has been refactored in the last commit

**Review by Machi3mfl — APPROVED** [review]

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark:

File: SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js [hunk 2]
```diff
@@ -77,21 +77,13 @@ define(['../module'], function (app) {
...
-          }
-        }
-        throw 'Key not found'
-      } catch (e) {
-        this.notification.showErrorToast(
-          'Extensions management failed: ' + (e.message || e)
-        )
+      const extensionsKey = this.sessionStorage?.extensions || false
+
+      if (extensionsKey && extensionsKey[apiId]) {
```
[the remark this answers is not in the document]
Comment (AlexRuiz7) [reply SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js:82]: A new check has been added in the last commit to prevent this case.
